[
    {
        "content": "<p>Re: CI with souffle, I've noticed a few times now that it we change the rules and they contain an error (for souffle, not logically), then the tests still pass because there is no successful run of souffle, the outputs are not updated and the fact that souffle fails goes unnoticed. We should probably address that (which I can do myself, right now I am on mobile and wanted to make sure to have this written down somewhere)</p>",
        "id": 259713814,
        "sender_full_name": "Domenic Quirl",
        "timestamp": 1635575107
    },
    {
        "content": "<p>ah yes I wanted to look at that, however on CI it shouldn’t matter, the runners are spawned from scratch each time</p>",
        "id": 259718121,
        "sender_full_name": "lqd",
        "timestamp": 1635582168
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"337115\">@Domenic Quirl</span> should be good now <a href=\"https://github.com/nikomatsakis/polonius.next/pull/4/commits/acfec4562ad1023e2966e7cbee2664068b1db6ac\">https://github.com/nikomatsakis/polonius.next/pull/4/commits/acfec4562ad1023e2966e7cbee2664068b1db6ac</a></p>",
        "id": 259719181,
        "sender_full_name": "lqd",
        "timestamp": 1635583715
    },
    {
        "content": "<p>I'm not sure the \"fact collection\" part can fail and things would keep running, but if we notice that we can just recreate the output folder each time and be done with it</p>",
        "id": 259719318,
        "sender_full_name": "lqd",
        "timestamp": 1635583936
    },
    {
        "content": "<p>(it doesn't look like it would continue to run but I've not read that code closely)</p>",
        "id": 259719358,
        "sender_full_name": "lqd",
        "timestamp": 1635584039
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"337115\">Domenic Quirl</span> <a href=\"#narrow/stream/186049-t-compiler.2Fwg-polonius/topic/Tests.20with.20souffle/near/259713814\">said</a>:</p>\n<blockquote>\n<p>Re: CI with souffle, I've noticed a few times now that it we change the rules and they contain an error (for souffle, not logically), then the tests still pass because there is no successful run of souffle, the outputs are not updated and the fact that souffle fails goes unnoticed. We should probably address that (which I can do myself, right now I am on mobile and wanted to make sure to have this written down somewhere)</p>\n</blockquote>\n<p>This is super annoying</p>",
        "id": 259873637,
        "sender_full_name": "nikomatsakis",
        "timestamp": 1635778520
    },
    {
        "content": "<p>I’ve fixed it in the fact gen PR</p>",
        "id": 259875228,
        "sender_full_name": "lqd",
        "timestamp": 1635779243
    }
]