[
    {
        "content": "<blockquote>\n<p>error: Tool <code>rls</code> has regressed from test-pass to test-fail during beta week.</p>\n</blockquote>\n<p><a href=\"https://github.com/rust-lang/rust/pull/72586\">https://github.com/rust-lang/rust/pull/72586</a> failed azune with the following error.</p>",
        "id": 199513711,
        "sender_full_name": "lcnr",
        "timestamp": 1591113421
    },
    {
        "content": "<p>How can I test this locally?</p>",
        "id": 199513726,
        "sender_full_name": "lcnr",
        "timestamp": 1591113428
    },
    {
        "content": "<p>Running<code>./x.py test check-tools</code> results in</p>\n<div class=\"codehilite\"><pre><span></span><code>error: Tool `book` was not recorded in tool state.\nerror: Tool `nomicon` was not recorded in tool state.\nerror: Tool `reference` was not recorded in tool state.\nerror: Tool `rust-by-example` was not recorded in tool state.\nerror: Tool `edition-guide` was not recorded in tool state.\nerror: Tool `rls` was not recorded in tool state.\nerror: Tool `rustfmt` was not recorded in tool state.\nerror: Tool `miri` was not recorded in tool state.\nerror: Tool `embedded-book` was not recorded in tool state.\nfailed to run: /home/programming/rust6/build/bootstrap/debug/bootstrap test check-tools\n</code></pre></div>",
        "id": 199513783,
        "sender_full_name": "lcnr",
        "timestamp": 1591113456
    },
    {
        "content": "<p>Does <code>./x.py test src/tools/rls</code> work?.</p>",
        "id": 199513971,
        "sender_full_name": "bjorn3",
        "timestamp": 1591113532
    },
    {
        "content": "<p>It locally compiles (and tests) without any errors <span aria-label=\"oh no\" class=\"emoji emoji-1f615\" role=\"img\" title=\"oh no\">:oh_no:</span></p>\n<p>Any tips on how to proceed here?</p>",
        "id": 199527461,
        "sender_full_name": "lcnr",
        "timestamp": 1591119712
    },
    {
        "content": "<blockquote>\n<p>2020-06-02T14:27:11.9794259Z [2020-06-02T14:27:11Z ERROR rls::server] Can't read message<br>\n2020-06-02T14:27:11.9796261Z thread 'main' panicked at 'called <code>Result::unwrap()</code> on an <code>Err</code> value: Os { code: 32, kind: BrokenPipe, message: \"Broken pipe\" }', src/tools/rls/rls/src/server/io.rs:190:9<br>\n2020-06-02T14:27:11.9797068Z note: run with <code>RUST_BACKTRACE=1</code> environment variable to display a backtrace</p>\n</blockquote>",
        "id": 199529118,
        "sender_full_name": "lcnr",
        "timestamp": 1591120541
    },
    {
        "content": "<p>Is this a spurious error? And if so, can someone retry <a href=\"https://github.com/rust-lang/rust/pull/72586\">https://github.com/rust-lang/rust/pull/72586</a></p>",
        "id": 199529206,
        "sender_full_name": "lcnr",
        "timestamp": 1591120566
    },
    {
        "content": "<p>Not sure how that could possibly break RLS, retrying</p>",
        "id": 199529606,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1591120739
    },
    {
        "content": "<p>Failed again, this time the log fairly short and seems completely unrelated</p>",
        "id": 199594119,
        "sender_full_name": "lcnr",
        "timestamp": 1591174294
    }
]