[
    {
        "content": "<p>Are you also getting now an <code>./x.py check</code> error like this?</p>\n<blockquote>\n<p>thread 'rustc' panicked at 'no entry found for key', compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs:492:</p>\n</blockquote>",
        "id": 262058191,
        "sender_full_name": "Dmitry S.",
        "timestamp": 1637323692
    },
    {
        "content": "<p>git version <a href=\"https://github.com/rust-lang/rust/commit/e8423e6c449ad3f4b0dab442175462004554e499\">e8423e6c449ad3f4b0dab442175462004554e499</a>,  build on an \"old-style\" Intel Mac (macos 11.6.1), full output in gist: <a href=\"https://gist.github.com/dmitris/be1682fade33a8bb5f3b5db6204fb52c\">https://gist.github.com/dmitris/be1682fade33a8bb5f3b5db6204fb52c</a></p>\n<p>Should I create a bug report, or is it already noted?</p>",
        "id": 262058752,
        "sender_full_name": "Dmitry S.",
        "timestamp": 1637324073
    },
    {
        "content": "<p>created <a href=\"https://github.com/rust-lang/rust/issues/91038\">https://github.com/rust-lang/rust/issues/91038</a></p>",
        "id": 262059769,
        "sender_full_name": "Dmitry S.",
        "timestamp": 1637324775
    }
]