[
    {
        "content": "<p>Hi! So I'm trying to run <code>./x.py doc --stage 1</code>, and I'm getting this error:</p>\n<div class=\"codehilite\"><pre><span></span>error: couldn&#39;t load codegen backend &quot;$path/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so&quot;: &quot;librustc_codegen_ssa-aff88005442ed60f.so: cannot open shared object file: No such file or directory&quot;\n</pre></div>",
        "id": 152505678,
        "sender_full_name": "detrumi",
        "timestamp": 1545730541
    },
    {
        "content": "<p>Building stage 1 works fine, and AFAIK you should be able to get docs in stage 1, right?</p>",
        "id": 152505721,
        "sender_full_name": "detrumi",
        "timestamp": 1545730598
    },
    {
        "content": "<p>This seems more like a <code>x.py</code> issue rather than a rustc/rustdoc one. I believe that behind the scenes <code>x.py</code> sets the appropriate <code>$LD_LIBRARY_PATH</code> (which explains system where to look for dynamic libraries) and it might be neglecting to do so for rustdoc?</p>",
        "id": 152507665,
        "sender_full_name": "nagisa",
        "timestamp": 1545734677
    },
    {
        "content": "<p>Ah. Hmm, building stage 2 fixed the problem at least</p>",
        "id": 152510533,
        "sender_full_name": "detrumi",
        "timestamp": 1545740933
    },
    {
        "content": "<p>Quite possibly a dependency graph issue</p>",
        "id": 152511092,
        "sender_full_name": "nagisa",
        "timestamp": 1545742294
    }
]