[
    {
        "content": "<p>Since I started using rust-analyzer, I am regularly getting errors like this when calling <code>x.py</code>:</p>\n<div class=\"codehilite\"><pre><span></span><code>error[E0460]: found possibly newer version of crate `std` which `log` depends on\n  --&gt; src/librustc_driver/lib.rs:12:1\n   |\n12 | extern crate log;\n   | ^^^^^^^^^^^^^^^^^\n   |\n   = note: perhaps that crate needs to be recompiled?\n   = note: the following crate versions were found:\n           crate `std`: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-85c1f7840b2e949a.rmeta\n           crate `log`: /home/r/src/rust/rustc.2/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/liblog-e908fe5e323e7fd9.rlib\n\nerror: aborting due to previous error\n\nerror: could not compile `rustc_driver`.\n</code></pre></div>\n\n\n<p>Is anyone else having that problem?</p>",
        "id": 198528974,
        "sender_full_name": "RalfJ",
        "timestamp": 1590229482
    }
]