<html>
<head><meta charset="utf-8"><title>Concerning (or noisy?) `./x.py test library/std` output · t-compiler/help · Zulip Chat Archive</title></head>
<h2>Stream: <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/index.html">t-compiler/help</a></h2>
<h3>Topic: <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/topic/Concerning.20(or.20noisy.3F).20.60.2E.2Fx.2Epy.20test.20library.2Fstd.60.20output.html">Concerning (or noisy?) `./x.py test library/std` output</a></h3>

<hr>

<base href="https://rust-lang.zulipchat.com">

<head><link href="https://zulip-archive.rust-lang.org/style.css" rel="stylesheet"></head>

<a name="248774824"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/182449-t-compiler/help/topic/Concerning%20%28or%20noisy%3F%29%20%60./x.py%20test%20library/std%60%20output/near/248774824" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thom Chiovoloni <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/topic/Concerning.20(or.20noisy.3F).20.60.2E.2Fx.2Epy.20test.20library.2Fstd.60.20output.html#248774824">(Aug 08 2021 at 15:04)</a>:</h4>
<p>I havent contributed to libstd recently, but if I run <code>./x.py test library/std</code> (on <code>master</code> without changes — any stage I think), I get errors like the following on macOS:</p>
<div class="codehilite"><pre><span></span><code>malloc: can&#39;t allocate region
:*** mach_vm_map(size=13835058055282167808, flags: 100) failed (error code=3)
std-d6a579ba8b5f87fe(88712,0x70000c738000) malloc: *** set a breakpoint in malloc_error_break to debug
</code></pre></div>
<p>This was pretty scary, since when I first saw it, I had added some unsafe code. But it happens on <code>master</code> too, and looking more closely... maybe it's just saying it failed to allocate an enormous region that we've requested? Not sure.</p>
<p>Is there any way to do any of the following:</p>
<ol>
<li>fire up the test in question under LLDB. If i try to run the test executable, i get an rpath issue, so I guess there's some magic that x.py does to make this work.</li>
<li>disable the test, whatever test it may be (no idea, nor how to figure that out without part 1).</li>
<li>fix whatever the issue is in any other way?</li>
</ol>
<p>Note that this isn't related to the allocator the compiler uses — the jemalloc setting has no effect.</p>
<hr>
<p>Actually, looking again, I also get stuff like</p>
<div class="codehilite"><pre><span></span><code>..........thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;test panic in inner thread to poison RwLock&#39;, library/std/src/sync/rwlock/tests.rs:238:9
...thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;test panic in inner thread to poison RwLock&#39;, library/std/src/sync/rwlock/tests.rs:214:9
..thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;explicit panic&#39;, library/std/src/sync/rwlock/tests.rs:150:9
.thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;explicit panic&#39;, library/std/src/sync/rwlock/tests.rs:78:9
.thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;explicit panic&#39;, library/std/src/sync/rwlock/tests.rs:90:9
.thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;explicit panic&#39;, library/std/src/sync/rwlock/tests.rs:52:9
.thread &#39;&lt;unnamed&gt;&#39; panicked at &#39;explicit panic&#39;, library/std/src/sync/rwlock/tests.rs:65:9
</code></pre></div>
<p>in the output as well. It seems that these aren't test failures...  Just noisy panics that happen as part of tests. Should something be getting redirected which is not? That might explain the malloc complaint too.</p>
<p>Is there any way to make it only speak up about the errors, the way the libcore tests do? I <em>think</em> it didn't used to do this...</p>



<a name="248777726"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/182449-t-compiler/help/topic/Concerning%20%28or%20noisy%3F%29%20%60./x.py%20test%20library/std%60%20output/near/248777726" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Eric Huss <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/topic/Concerning.20(or.20noisy.3F).20.60.2E.2Fx.2Epy.20test.20library.2Fstd.60.20output.html#248777726">(Aug 08 2021 at 16:20)</a>:</h4>
<p><span class="user-mention" data-user-id="209168">@Thom Chiovoloni</span> One way to narrow down <em>which</em> test is printing the message is to run one at a time. With x.py, set <code>verbose-tests = true</code> in <code>config.toml</code>, and run it with RUST_TEST_THREADS=1 environment variable. It will print the test name just before it starts when it is single threaded. In this case, you can see it is <code>test_try_reserve</code> which attempts to allocate MAX_USIZE elements which will always fail. I think it would be possible to set one of the environment variables to hide that message (<code>MallocDebugReport</code> maybe?), but I don't think that is a good idea and probably not worth the hassle.</p>
<p>libstd's tests use dynamic linking. I'm not entirely sure why the rpath isn't set, but you can make it work manually with <code>DYLD_LIBRARY_PATH=build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/lib</code>.</p>



<a name="248778369"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/182449-t-compiler/help/topic/Concerning%20%28or%20noisy%3F%29%20%60./x.py%20test%20library/std%60%20output/near/248778369" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> bjorn3 <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/topic/Concerning.20(or.20noisy.3F).20.60.2E.2Fx.2Epy.20test.20library.2Fstd.60.20output.html#248778369">(Aug 08 2021 at 16:38)</a>:</h4>
<p>The rpath is only set when you explicitly use <code>-Crpath</code>.</p>



<a name="248779981"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/182449-t-compiler/help/topic/Concerning%20%28or%20noisy%3F%29%20%60./x.py%20test%20library/std%60%20output/near/248779981" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> The 8472 <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/topic/Concerning.20(or.20noisy.3F).20.60.2E.2Fx.2Epy.20test.20library.2Fstd.60.20output.html#248779981">(Aug 08 2021 at 17:20)</a>:</h4>
<p>some of the tests are intentionally triggering panics, leaks or huge allocations to test the unhappy path. so it might be intentional, but you'll have to look at the individual test to see if it really is</p>



<a name="248780640"></a>
<h4><a href="https://rust-lang.zulipchat.com#narrow/stream/182449-t-compiler/help/topic/Concerning%20%28or%20noisy%3F%29%20%60./x.py%20test%20library/std%60%20output/near/248780640" class="zl"><img src="https://zulip-archive.rust-lang.org/assets/img/zulip.svg" alt="view this post on Zulip" style="width:20px;height:20px;"></a> Thom Chiovoloni <a href="https://zulip-archive.rust-lang.org/stream/182449-t-compiler/help/topic/Concerning.20(or.20noisy.3F).20.60.2E.2Fx.2Epy.20test.20library.2Fstd.60.20output.html#248780640">(Aug 08 2021 at 17:40)</a>:</h4>
<p>The panics it just seems like they shouldn't be output (they aren't for the testrunner of normal rust code, after all). And for the malloc, im surprised im the only person hitting it is all. but i can think of ways to deal with it too, i guess</p>



<hr><p>Last updated: Apr 12 2022 at 20:01 UTC</p>
</html>