[
    {
        "content": "<p><a href=\"https://github.com/rust-lang/rust/issues/78432\">#78432</a>, <a href=\"https://github.com/rust-lang-ci/rust/runs/1323896596\">failed</a> test test/debuginfo/pretty-std-collections.rs because of</p>\n<div class=\"codehilite\"><pre><span></span><code>stderr:\n------------------------------------------\nerror: need to add support for DW_TAG_base_type &#39;()&#39; encoded with DW_ATE = 0x7, bit_size = 0\nclang: CommandLine Error: Option &#39;h&#39; registered more than once!\nLLVM ERROR: inconsistency in registered CommandLine options\nclang: CommandLine Error: Option &#39;h&#39; registered more than once!\nLLVM ERROR: inconsistency in registered CommandLine options\n</code></pre></div>\n\n\n<p>At least on the surface, the PR should've not affected anything to do with the error being reported.  Just want to check before I go investigate if anyone has any clues if this is a spurious failure? If so can someone restart the build?</p>",
        "id": 214918325,
        "sender_full_name": "Aman Arora",
        "timestamp": 1603936305
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"281950\">@Aman Arora</span> that seems a weird error, retry?</p>",
        "id": 214938861,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1603961042
    },
    {
        "content": "<p>Yeah, seems spurious, I had a rollup fail with the same error</p>",
        "id": 214946965,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603965899
    },
    {
        "content": "<p>that's a weird spurious</p>",
        "id": 214953427,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1603970365
    },
    {
        "content": "<p>hmm, actually that rollup was <a href=\"https://github.com/rust-lang/rust/pull/78501\">https://github.com/rust-lang/rust/pull/78501</a>, which contained the PR above, so maybe that did cause it</p>",
        "id": 214966788,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603978586
    },
    {
        "content": "<p>no idea how that would cause it though</p>",
        "id": 214966821,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603978609
    },
    {
        "content": "<p>Hmm this got cancelled, looks like all agents had passed: <a href=\"https://github.com/rust-lang-ci/rust/runs/1328044356\">https://github.com/rust-lang-ci/rust/runs/1328044356</a></p>",
        "id": 215000183,
        "sender_full_name": "Aman Arora",
        "timestamp": 1603992239
    },
    {
        "content": "<blockquote>\n<p>GitHub Actions has encountered an internal error when running your job.</p>\n</blockquote>",
        "id": 215000332,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603992292
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"211727\">Jonas Schievink</span> <a href=\"#narrow/stream/242791-t-infra/topic/apple-x86_64.20gha.20checks/near/215000332\">said</a>:</p>\n<blockquote>\n<blockquote>\n<p>GitHub Actions has encountered an internal error when running your job.</p>\n</blockquote>\n</blockquote>\n<p>curious, where do you see this?</p>",
        "id": 215001089,
        "sender_full_name": "Aman Arora",
        "timestamp": 1603992620
    },
    {
        "content": "<p>In the run overview: <a href=\"https://github.com/rust-lang-ci/rust/actions/runs/336037245\">https://github.com/rust-lang-ci/rust/actions/runs/336037245</a></p>",
        "id": 215001858,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603992950
    },
    {
        "content": "<p>I just had the same error happen to me in an unrelated repo: <a href=\"https://github.com/jonas-schievink/rubble/actions/runs/336357031\">https://github.com/jonas-schievink/rubble/actions/runs/336357031</a></p>",
        "id": 215001944,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603992977
    },
    {
        "content": "<p>Ah</p>",
        "id": 215001998,
        "sender_full_name": "Aman Arora",
        "timestamp": 1603993010
    },
    {
        "content": "<p>Thanks!</p>",
        "id": 215002012,
        "sender_full_name": "Aman Arora",
        "timestamp": 1603993017
    },
    {
        "content": "<p>This rollup failed with the same error: <a href=\"https://github.com/rust-lang/rust/pull/78528#issuecomment-718943540\">https://github.com/rust-lang/rust/pull/78528#issuecomment-718943540</a></p>\n<p><a href=\"https://github.com/rust-lang-ci/rust/actions/runs/336351650\">https://github.com/rust-lang-ci/rust/actions/runs/336351650</a></p>",
        "id": 215010095,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1603996712
    },
    {
        "content": "<p><a href=\"https://github.com/actions/runner/issues/744\">https://github.com/actions/runner/issues/744</a> intermittent failure? Nothing was explicitly linked to fixing it</p>",
        "id": 215010527,
        "sender_full_name": "Aman Arora",
        "timestamp": 1603996952
    },
    {
        "content": "<p>I don't have the time to investigate this right now, if nobody beats me to it I'll look at it next morning</p>",
        "id": 215014220,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1603998687
    },
    {
        "content": "<p>I think the rollup went through, can someone restart <a href=\"https://github.com/rust-lang/rust/pull/78432\">https://github.com/rust-lang/rust/pull/78432</a></p>",
        "id": 215050485,
        "sender_full_name": "Aman Arora",
        "timestamp": 1604024436
    },
    {
        "content": "<p>done</p>",
        "id": 215050588,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1604024618
    },
    {
        "content": "<p>thank you <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span></p>",
        "id": 215050761,
        "sender_full_name": "Aman Arora",
        "timestamp": 1604024861
    },
    {
        "content": "<p>aight this got merged <span aria-label=\"smile\" class=\"emoji emoji-1f642\" role=\"img\" title=\"smile\">:smile:</span></p>",
        "id": 215120495,
        "sender_full_name": "Aman Arora",
        "timestamp": 1604076302
    },
    {
        "content": "<p>I've gotten that spurious error twice in a row on <a href=\"https://github.com/rust-lang/rust/pull/75534\">https://github.com/rust-lang/rust/pull/75534</a></p>",
        "id": 215252046,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604249425
    },
    {
        "content": "<p>According to &lt;<a href=\"https://github.com/actions/virtual-environments\">https://github.com/actions/virtual-environments</a>&gt;, they're rolling out an update for the apple runners, which is at 85% now. Maybe this happens only on the non-updated or only on the updated ones?</p>",
        "id": 215253973,
        "sender_full_name": "Mara",
        "timestamp": 1604252303
    },
    {
        "content": "<p>the PR went through on the third try</p>",
        "id": 215258060,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604258664
    },
    {
        "content": "<p>Always the third try <span aria-label=\"joy\" class=\"emoji emoji-1f602\" role=\"img\" title=\"joy\">:joy:</span></p>",
        "id": 215260465,
        "sender_full_name": "Aman Arora",
        "timestamp": 1604262011
    },
    {
        "content": "<p>another one of those failures: <a href=\"https://github.com/rust-lang/rust/pull/78640#issuecomment-720150429\">https://github.com/rust-lang/rust/pull/78640#issuecomment-720150429</a> :(</p>",
        "id": 215262031,
        "sender_full_name": "Mara",
        "timestamp": 1604264373
    },
    {
        "content": "<p>I'll take a look first thing tomorrow</p>",
        "id": 215262168,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604264574
    },
    {
        "content": "<p>Looks like this same error message has been hit before: <a href=\"https://github.com/rust-lang/rust/issues/63266\">https://github.com/rust-lang/rust/issues/63266</a></p>",
        "id": 215262261,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604264719
    },
    {
        "content": "<p>though that doesn't explain why it's showing up inconsistently on CI</p>",
        "id": 215262263,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604264728
    },
    {
        "content": "<p>I think I know what it is</p>",
        "id": 215262321,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604264806
    },
    {
        "content": "<p>for the builds we're using our own clang, version 10</p>",
        "id": 215262325,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604264826
    },
    {
        "content": "<p>but they upgraded to llvm 11 <a href=\"https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20201026.2\">https://github.com/actions/virtual-environments/releases/tag/macOS-10.15%2F20201026.2</a></p>",
        "id": 215262327,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604264842
    },
    {
        "content": "<p>that's plausible with the rollouts</p>",
        "id": 215262330,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604264848
    },
    {
        "content": "<p>tomorrow I'll open a ticket</p>",
        "id": 215262332,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604264855
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"125254\">@kennytm</span> <a href=\"https://github.com/rust-lang/rust/pull/78280\">https://github.com/rust-lang/rust/pull/78280</a> is this</p>",
        "id": 215299855,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312059
    },
    {
        "content": "<p>(copy/pasted the wrong thing before)</p>",
        "id": 215299868,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312067
    },
    {
        "content": "<p>and yeah I tested a bit in a local repository and the llvm version mismatch seems to be the cause</p>",
        "id": 215299898,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312093
    },
    {
        "content": "<p>we're bringing our own llvm 10 in the CI builders, but the recent virtual environments upgrade bumped the system version to llvm 11</p>",
        "id": 215299944,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312128
    },
    {
        "content": "<p>so we're using the system lldb 11 with llvm 10</p>",
        "id": 215299955,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312138
    },
    {
        "content": "<p>I'm... not sure how to fix this tho</p>",
        "id": 215300088,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312229
    },
    {
        "content": "<p>llvm doesn't ship prebuilt lldb :/</p>",
        "id": 215300110,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604312240
    },
    {
        "content": "<p>opened a ticket asking to roll us back temporarily to the old environment</p>",
        "id": 215301789,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604313257
    },
    {
        "content": "<p>ok, so, this is weird because some builds with the new build environment are working</p>",
        "id": 215303072,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604313947
    },
    {
        "content": "<p>ugh debugging this without a mac is painful</p>",
        "id": 215303773,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604314442
    },
    {
        "content": "<p>Opened <a href=\"https://github.com/rust-lang/rust/issues/78665\">#78665</a> before finding this topic, thanks for investigating :)</p>",
        "id": 215304123,
        "sender_full_name": "Yuki Okushi",
        "timestamp": 1604314694
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"121055\">Pietro Albini</span> <a href=\"#narrow/stream/242791-t-infra/topic/apple-x86_64.20gha.20checks/near/215303072\">said</a>:</p>\n<blockquote>\n<p>ok, so, this is weird because some builds with the new build environment are working</p>\n</blockquote>\n<p>yeah, <a href=\"https://github.com/rust-lang/rust/issues/75020\">#75020</a> is fine but <a href=\"https://github.com/rust-lang/rust/issues/78661\">#78661</a> failed to test :/</p>",
        "id": 215304149,
        "sender_full_name": "Yuki Okushi",
        "timestamp": 1604314732
    },
    {
        "content": "<p>so, my working theory is that the problem lies somewhere with our <code>src/etc/lldb_batchmode.py</code></p>",
        "id": 215306419,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316458
    },
    {
        "content": "<p>and how it interacts with the new lldb</p>",
        "id": 215306426,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316468
    },
    {
        "content": "<p>I think the \"clang\" part of \"clang: CommandLine Error: Option 'h' registered more than once!\" is a red herring, because it doesn't make any sense we'd provide <code>clang</code> with <code>-h</code>/<code>--help</code></p>",
        "id": 215306494,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316516
    },
    {
        "content": "<p>but while ripgrepping around I found <code>src/etc/lldb_commands</code>, which calls lldb's <code>type summary add</code>, which accepts a <code>-h</code> option that actually makes sense</p>",
        "id": 215306605,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316607
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>-h ( --hide-empty )\n     Do not expand aggregate data types with no children.\n</code></pre></div>",
        "id": 215306632,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316627
    },
    {
        "content": "<p>also, in <a href=\"https://github.com/rust-lang-ci/rust/runs/1337490520\">https://github.com/rust-lang-ci/rust/runs/1337490520</a> the error message is this one:</p>\n<div class=\"codehilite\"><pre><span></span><code>clangclang: CommandLine Error: Option &#39;: CommandLine Error: Option &#39;hh&#39; registered more than once!\n&#39; registered more than once!\nLLVM ERROR: inconsistency in registered CommandLine options\nLLVM ERROR: inconsistency in registered CommandLine options\n</code></pre></div>",
        "id": 215306657,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316654
    },
    {
        "content": "<p>that error message is printed by <a href=\"https://github.com/llvm/llvm-project/blob/9ffb5b0469ae593f8b7e1d7d9ef6ea46cd366e6e/llvm/lib/Support/CommandLine.cpp#L181-L185\">https://github.com/llvm/llvm-project/blob/9ffb5b0469ae593f8b7e1d7d9ef6ea46cd366e6e/llvm/lib/Support/CommandLine.cpp#L181-L185</a>, and it overlaps exactly between the <code>&lt;&lt;</code>s</p>",
        "id": 215306769,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316738
    },
    {
        "content": "<p>since it happens spuriously, and in one case it actually happened two times, I think it's <code>lldb_batchmode.py</code> that sends the commands to the new <code>lldb</code> too fast, or the new <code>lldb</code> is too slow to accept them</p>",
        "id": 215306821,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316789
    },
    {
        "content": "<p>and so it breaks while sending <code>src/etc/lldb_commands</code></p>",
        "id": 215306845,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316813
    },
    {
        "content": "<p>I haven't dig into <code>lldb_batchmode.py</code> yet, and not having a mac is making things hard (I'm tempted to just throw money at apple) :/</p>",
        "id": 215306979,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316903
    },
    {
        "content": "<p>/end</p>",
        "id": 215306988,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604316909
    },
    {
        "content": "<p>would be nice if apple would sponsor some macs for the rust infra team.</p>",
        "id": 215307082,
        "sender_full_name": "Mara",
        "timestamp": 1604316968
    },
    {
        "content": "<p>heh</p>",
        "id": 215307297,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604317112
    },
    {
        "content": "<p>I guess it's now time to mindlessly read the lldb_batchmode source code and try to guess why it's broken</p>",
        "id": 215307441,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604317254
    },
    {
        "content": "<p>ok no that's not the problem</p>",
        "id": 215308453,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318066
    },
    {
        "content": "<p><code>lldb_batchmode.py</code> doesn't load <code>lldb_commands</code></p>",
        "id": 215308463,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318076
    },
    {
        "content": "<p>and the error is happening before the script actually starts, since <a href=\"https://github.com/rust-lang/rust/blob/234099d1d12bef9d6e81a296222fbc272dc51d89/src/etc/lldb_batchmode.py#L174-L178\"><code>lldb_batchmode.py</code> prints stuff at startup</a></p>",
        "id": 215308519,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318144
    },
    {
        "content": "<p>ok this makes less and less sense the more I look into it</p>",
        "id": 215308937,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318417
    },
    {
        "content": "<p>we're not passing anything to clang before <code>lldb_batchmode.py</code> starts up</p>",
        "id": 215308979,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318463
    },
    {
        "content": "<p>so either python is just eating <code>print</code>s (I know about buffering and <code>PYTHONUNBUFFERED</code>, but like, it should flush when it exits) or... dunno</p>",
        "id": 215309110,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318538
    },
    {
        "content": "<p><a href=\"https://github.com/llvm/llvm-project/blob/9ffb5b0469ae593f8b7e1d7d9ef6ea46cd366e6e/llvm/include/llvm/Support/ErrorHandling.h#L69-L70\">great so LLVM just <code>abort()</code>s when there is an error</a></p>",
        "id": 215309353,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318734
    },
    {
        "content": "<p>so it's possible that python doesn't have a chance to print the buffered output</p>",
        "id": 215309440,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318768
    },
    {
        "content": "<p><del>all of this would've been so nice with a device to test stuff on</del></p>",
        "id": 215309586,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604318879
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"116122\">@simulacrum</span> opened <a href=\"https://github.com/rust-lang/rust/pull/78667\">https://github.com/rust-lang/rust/pull/78667</a> to hopefully get vaguely useful data out of those failures</p>",
        "id": 215311249,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604319975
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"121055\">@Pietro Albini</span> fwiw you can probably use our aarch64 mac?</p>",
        "id": 215311348,
        "sender_full_name": "simulacrum",
        "timestamp": 1604320061
    },
    {
        "content": "<p>I'm not sure our test suite actually works there</p>",
        "id": 215311417,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604320089
    },
    {
        "content": "<p>Hm ok</p>",
        "id": 215311465,
        "sender_full_name": "simulacrum",
        "timestamp": 1604320124
    },
    {
        "content": "<p>I can try running something in a while loop on my mac if that's helpful?</p>",
        "id": 215311499,
        "sender_full_name": "simulacrum",
        "timestamp": 1604320145
    },
    {
        "content": "<p>running debug tests in a loop could probably show it?</p>",
        "id": 215311649,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604320227
    },
    {
        "content": "<p>but I <em>guess</em> we need lldb from system llvm 11</p>",
        "id": 215311692,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604320258
    },
    {
        "content": "<p>dunno if that's what you have?</p>",
        "id": 215311717,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604320271
    },
    {
        "content": "<p>I'll need to pull it out and I probably don't have time today unfortunately</p>",
        "id": 215321730,
        "sender_full_name": "simulacrum",
        "timestamp": 1604325774
    },
    {
        "content": "<p>ok the extra debug information landed, ping me when it happens again</p>",
        "id": 215337180,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604332456
    },
    {
        "content": "<p>btw, got an answer from github support, they can't halt the rollout in our organization</p>",
        "id": 215349503,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604337394
    },
    {
        "content": "<p>which... seems weird if we have rollouts, but it wouldn't be the most surprising thing I learned about github actions</p>",
        "id": 215349562,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604337419
    },
    {
        "content": "<p>ok the buffering intuition was correct</p>",
        "id": 215379188,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604351412
    },
    {
        "content": "<p>we were losing a bunch of messages</p>",
        "id": 215379194,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604351416
    },
    {
        "content": "<p><a href=\"https://github.com/rust-lang-ci/rust/runs/1343837326\">https://github.com/rust-lang-ci/rust/runs/1343837326</a></p>",
        "id": 215379196,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604351417
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>---- [debuginfo-lldb] debuginfo/pretty-std-collections.rs stdout ----\nNOTE: compiletest thinks it is using LLDB version 1200\nNOTE: compiletest thinks it is using LLDB without native rust support\n\nerror: Error while running LLDB\nstatus: exit code: 1\ncommand: &quot;/usr/bin/python3&quot; &quot;/Users/runner/work/rust/rust/src/etc/lldb_batchmode.py&quot; &quot;/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/debuginfo/pretty-std-collections.lldb/a&quot; &quot;/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/debuginfo/pretty-std-collections.lldb/pretty-std-collections.debugger.script&quot;\nstdout:\n------------------------------------------\nLLDB batch-mode script\n----------------------\nDebugger commands script is &#39;/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/debuginfo/pretty-std-collections.lldb/pretty-std-collections.debugger.script&#39;.\nTarget executable is &#39;/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/debuginfo/pretty-std-collections.lldb/a&#39;.\nCurrent working directory is &#39;/Users/runner/work/rust/rust&#39;\nCreating a target for &#39;/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/debuginfo/pretty-std-collections.lldb/a&#39;\nsettings set auto-confirm true\n\nversion\nlldb-1200.0.32.1 Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)\ncommand script import /Users/runner/work/rust/rust/./src/etc/lldb_lookup.py\ntype synthetic add -l lldb_lookup.synthetic_lookup -x &#39;.*&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)String$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^&amp;str$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^&amp;\\[.+\\]$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(std::ffi::([a-z_]+::)+)OsString$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)Vec&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)VecDeque&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)BTreeSet&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)BTreeMap&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(std::collections::([a-z_]+::)+)HashMap&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(std::collections::([a-z_]+::)+)HashSet&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)Rc&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(alloc::([a-z_]+::)+)Arc&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(core::([a-z_]+::)+)Cell&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(core::([a-z_]+::)+)Ref&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(core::([a-z_]+::)+)RefMut&lt;.+&gt;$&#39; --category Rust\ntype summary add -F lldb_lookup.summary_lookup  -e -x -h &#39;^(core::([a-z_]+::)+)RefCell&lt;.+&gt;$&#39; --category Rust\ntype category enable Rust\n\nbreakpoint set --file &#39;pretty-std-collections.rs&#39; --line 158\nBreakpoint 1: where = a`pretty_std_collections::main::h1ef1d7ce5967b6a7 + 1513 at pretty-std-collections.rs:158:5, address = 0x0000000100029399\nError while trying to register breakpoint callback, id = 1\nrun\nProcess 68725 stopped * thread #1, queue = &#39;com.apple.main-thread&#39;, stop reason = breakpoint 1.1 frame #0: 0x0000000100029399 a`pretty_std_collections::main::h1ef1d7ce5967b6a7 at pretty-std-collections.rs:158:5 155 hash_set.insert(i); 156 } 157 -&gt; 158 zzz(); // #break ^ 159 } 160 161 fn zzz() { Target 0: (a) stopped. Process 68725 launched: &#39;/Users/runner/work/rust/rust/build/x86_64-apple-darwin/test/debuginfo/pretty-std-collections.lldb/a&#39; (x86_64)\nprint vec_deque\n(alloc::collections::vec_deque::VecDeque&lt;int&gt;) $0 = size=3 { [0] = 5 [1] = 3 [2] = 7 }\nprint vec_deque2\n(alloc::collections::vec_deque::VecDeque&lt;int&gt;) $1 = size=7 { [0] = 2 [1] = 3 [2] = 4 [3] = 5 [4] = 6 [5] = 7 [6] = 8 }\nprint hash_map\n\n------------------------------------------\nstderr:\n------------------------------------------\nerror: need to add support for DW_TAG_base_type &#39;()&#39; encoded with DW_ATE = 0x7, bit_size = 0\nclang: CommandLine Error: Option &#39;h&#39; registered more than once!\nLLVM ERROR: inconsistency in registered CommandLine options\n</code></pre></div>",
        "id": 215379363,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604351502
    },
    {
        "content": "<p>I'd love a review on <a href=\"https://github.com/rust-lang/rust/pull/78699\">https://github.com/rust-lang/rust/pull/78699</a></p>",
        "id": 215438378,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604401395
    },
    {
        "content": "<p>(from anyone, really)</p>",
        "id": 215438396,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604401402
    },
    {
        "content": "<p><span class=\"user-mention silent\" data-user-id=\"121055\">Pietro Albini</span> <a href=\"#narrow/stream/242791-t-infra/topic/apple-x86_64.20gha.20checks/near/215438378\">said</a>:</p>\n<blockquote>\n<p>I'd love a review on <a href=\"https://github.com/rust-lang/rust/pull/78699\">https://github.com/rust-lang/rust/pull/78699</a></p>\n</blockquote>\n<p>I'm not confident saying this on the PR itself, but it looks reasonable to me.  I'm not experienced in python/llvm stuff</p>",
        "id": 215439272,
        "sender_full_name": "Daniel Silverstone",
        "timestamp": 1604401930
    },
    {
        "content": "<p>Looks fine, I saw GetError is called below so presumably it's defined</p>",
        "id": 215441581,
        "sender_full_name": "Joshua Nelson",
        "timestamp": 1604403405
    },
    {
        "content": "<p>so, <code>error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0</code> is a false flag</p>",
        "id": 215695007,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604572976
    },
    {
        "content": "<p>I tried running the debuginfo test locally on my linux machine: the test passed, and when I disabled output capturing the error message was there</p>",
        "id": 215695053,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604573008
    },
    {
        "content": "<p>the other error we're seeing is \"Error while trying to register breakpoint callback, id = 1, message = error: could not get num args: can't find callable: breakpoint_callback\"</p>",
        "id": 215698961,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604575532
    },
    {
        "content": "<p>which... doesn't make sense, that function is defined</p>",
        "id": 215698980,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604575546
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"121055\">@Pietro Albini</span> I was looking at this a little last night.  The <code>can't find callable</code> is not mac-specific, it also happens on linux.  It's because the function isn't imported.  The lldb script interpreter has a \"session\" dictionary, and functions need to be specifically added to it to be called.</p>",
        "id": 215718563,
        "sender_full_name": "Eric Huss",
        "timestamp": 1604586656
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"120518\">@Eric Huss</span> weird, I don't recall that error happening locally for me</p>",
        "id": 215730987,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604591586
    },
    {
        "content": "<p>If you ran the test locally, at least for me it appears in <code>build/x86_64-unknown-linux-gnu/test/debuginfo/pretty-std-collections.lldb/pretty-std-collections.out</code>.    Maybe it depends on the version of lldb?  I have <code>lldb version 10.0.0</code> on linux and <code>lldb-1200.0.32.1</code> on macos.</p>",
        "id": 215731435,
        "sender_full_name": "Eric Huss",
        "timestamp": 1604591773
    },
    {
        "content": "<p>uh, I think that's because I have lldb 6 on my system <span aria-label=\"sweat smile\" class=\"emoji emoji-1f605\" role=\"img\" title=\"sweat smile\">:sweat_smile:</span></p>",
        "id": 215732182,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604592057
    },
    {
        "content": "<p>on it though the callback gets registered just fine</p>",
        "id": 215732212,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1604592068
    },
    {
        "content": "<p>I tried running the script in a loop on GitHub Actions for about 20 minutes (500 iterations), but wasn't able to get it to fail. <span aria-label=\"frown\" class=\"emoji emoji-1f641\" role=\"img\" title=\"frown\">:frown:</span></p>",
        "id": 215743542,
        "sender_full_name": "Eric Huss",
        "timestamp": 1604596304
    },
    {
        "content": "<p>It seems to happen a lot less often now, but it happened again just now: &lt;<a href=\"https://github.com/rust-lang-ci/rust/runs/1367502589\">https://github.com/rust-lang-ci/rust/runs/1367502589</a>&gt;</p>",
        "id": 215952967,
        "sender_full_name": "Mara",
        "timestamp": 1604752330
    },
    {
        "content": "<p>It happened again in <a href=\"https://github.com/rust-lang-ci/rust/runs/1369020942\">https://github.com/rust-lang-ci/rust/runs/1369020942</a></p>",
        "id": 215984940,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604802545
    },
    {
        "content": "<p>Another case in <a href=\"https://github.com/rust-lang/rust/pull/78201#issuecomment-723674636\">https://github.com/rust-lang/rust/pull/78201#issuecomment-723674636</a></p>",
        "id": 216032713,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604880424
    },
    {
        "content": "<p>and one more: <a href=\"https://github.com/rust-lang-ci/rust/runs/1370761818\">https://github.com/rust-lang-ci/rust/runs/1370761818</a></p>",
        "id": 216062408,
        "sender_full_name": "Dániel Buga",
        "timestamp": 1604915742
    },
    {
        "content": "<p>Would it make sense to temporarily disable this test while it's investigated further, or are the new failure logs providing additional information? This is resulting in a large number of spurious failures, and people who aren't aware of this issue may waste time trying to debug their own PR.</p>",
        "id": 216126761,
        "sender_full_name": "Aaron Hill",
        "timestamp": 1604947385
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"120518\">@Eric Huss</span> ok my mac mini arrived earlier than expected, and I'm running the test in a loop</p>",
        "id": 216353968,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605105671
    },
    {
        "content": "<p>and it's always succeeding</p>",
        "id": 216353982,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605105680
    },
    {
        "content": "<p>now I guess the next step is to try and reproduce the CI environment locally</p>",
        "id": 216354018,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605105694
    },
    {
        "content": "<p>Yea, feel free to ask any questions. I've tried a large number of different things, I could maybe summarize them?  I tried a bunch to replicate GHA's environment locally, but never succeeded in reproducing it.</p>\n<p>My current reproducer is <a href=\"https://github.com/ehuss/test/blob/pretty-std-collections/.github/workflows/main.yml\">here</a> with the script <a href=\"https://github.com/ehuss/test/blob/pretty-std-collections/lldb-test.sh\">lldb-test.sh</a>.  I tried some dyld debug printing, but nothing interesting showed up.</p>\n<p>Unfortunately I don't know much about how lldb is implemented, and the codebase is quite large.</p>",
        "id": 216354415,
        "sender_full_name": "Eric Huss",
        "timestamp": 1605105920
    },
    {
        "content": "<p>New data point: Xcode 11.7 doesn't seem to fail</p>",
        "id": 216364312,
        "sender_full_name": "Eric Huss",
        "timestamp": 1605110476
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"120518\">@Eric Huss</span> FWIW, I'm also seeing this on aarch64-apple-darwin.</p>",
        "id": 216817907,
        "sender_full_name": "Jake Goulding",
        "timestamp": 1605479181
    },
    {
        "content": "<p>Xcode 12.2 release, Big Sur, git commit <a href=\"https://github.com/rust-lang/rust/commit/9d78d1d02761b906038ba4d54c5f3427f920f5fb\">9d78d1d02761b906038ba4d54c5f3427f920f5fb</a> (with some local modifications)</p>",
        "id": 216817938,
        "sender_full_name": "Jake Goulding",
        "timestamp": 1605479277
    },
    {
        "content": "<p>reproduced via <code>x.py test --stage=2</code></p>",
        "id": 216817979,
        "sender_full_name": "Jake Goulding",
        "timestamp": 1605479295
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"116155\">@Jake Goulding</span> Was that running under the github actions runner, or were you running it manually?</p>",
        "id": 216818067,
        "sender_full_name": "Eric Huss",
        "timestamp": 1605479448
    },
    {
        "content": "<p>Manually on the DTK. ￼</p>",
        "id": 216818617,
        "sender_full_name": "Jake Goulding",
        "timestamp": 1605480033
    },
    {
        "content": "<p><span class=\"user-mention\" data-user-id=\"120518\">@Eric Huss</span> LOL</p>",
        "id": 216850195,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605520024
    },
    {
        "content": "<p>I tried a bunch to reproduce it with <code>./x.py test --stage 1</code>, and it never reproduced</p>",
        "id": 216850270,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605520075
    },
    {
        "content": "<p>ran <code>./x.py test --stage 2</code> and it <em>immediately</em> failed <span aria-label=\"smiley\" class=\"emoji emoji-1f603\" role=\"img\" title=\"smiley\">:smiley:</span></p>",
        "id": 216850336,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605520100
    },
    {
        "content": "<p>need to finish some release stuff, I'll then take a look at investigating it more in-depth</p>",
        "id": 216850371,
        "sender_full_name": "Pietro Albini",
        "timestamp": 1605520121
    }
]