[
    {
        "content": "<p>I got a test failure on CI for a PR, amended my commit to fix it, force-pushed, but the second CI run seems to be testing the same PR again without the latest changes. Has anyone seen something like this before? <a href=\"https://github.com/rust-lang/rust/pull/94954#issuecomment-1067770666\">https://github.com/rust-lang/rust/pull/94954#issuecomment-1067770666</a></p>",
        "id": 275352884,
        "sender_full_name": "Simon Sapin",
        "timestamp": 1647339228
    },
    {
        "content": "<p>In <a href=\"https://github.com/rust-lang/rust/runs/5551345546?check_suite_focus=true#step:3:45\">https://github.com/rust-lang/rust/runs/5551345546?check_suite_focus=true#step:3:45</a> it looks like CI is fetching <code>bda03e9cea4acef4df0e2a088b9af7fd09179d01</code> to <code>refs/remotes/pull/94954/merge</code> but that looks wrong:</p>\n<div class=\"codehilite\"><pre><span></span><code>$ git ls-remote origin refs/pull/94954/merge\n66513a7c015e88307887eb7a981f63e66d419dcd    refs/pull/94954/merge\n</code></pre></div>",
        "id": 275353152,
        "sender_full_name": "Simon Sapin",
        "timestamp": 1647339374
    },
    {
        "content": "<p>I made a dummy push and the third CI run appears to be checking out the correct commit. Could there be a race condition between pushes and CI triggers?</p>",
        "id": 275354816,
        "sender_full_name": "Simon Sapin",
        "timestamp": 1647340355
    },
    {
        "content": "<p>I think I've seen this before, though typically it's ~impossible to reproduce, and it's pretty rare.</p>",
        "id": 275379730,
        "sender_full_name": "simulacrum",
        "timestamp": 1647354365
    },
    {
        "content": "<p>According to <a href=\"https://github.com/rust-lang/rust/compare/c0489e05bee563e89dc918faac260bfc35114e32..de147317a4e89f441378263e1abf84b34df26788\">https://github.com/rust-lang/rust/compare/c0489e05bee563e89dc918faac260bfc35114e32..de147317a4e89f441378263e1abf84b34df26788</a>, the first force-push appears to be empty.  The second force-push looks to be correct (<a href=\"https://github.com/rust-lang/rust/compare/c0befc497aa045cf828ad88cbe9ce44b0ce3d7b2..ab13ccfbe87c88ca464f18f5b0f4d88fcc0b1fac\">https://github.com/rust-lang/rust/compare/c0befc497aa045cf828ad88cbe9ce44b0ce3d7b2..ab13ccfbe87c88ca464f18f5b0f4d88fcc0b1fac</a>).</p>",
        "id": 275379761,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647354386
    },
    {
        "content": "<p>The commits <a href=\"https://github.com/rust-lang/rust/commit/c0489e05bee563e89dc918faac260bfc35114e32\">c0489e05bee563e89dc918faac260bfc35114e32</a> and <a href=\"https://github.com/rust-lang/rust/commit/de147317a4e89f441378263e1abf84b34df26788\">de147317a4e89f441378263e1abf84b34df26788</a> look to be identical except for the timestamp.</p>",
        "id": 275380076,
        "sender_full_name": "Eric Huss",
        "timestamp": 1647354539
    },
    {
        "content": "<p>I think I messed up the contents of the force-push, but still saw CI run with an unexpected merge commit hash</p>",
        "id": 275386105,
        "sender_full_name": "Simon Sapin",
        "timestamp": 1647357068
    },
    {
        "content": "<p>Anyway, itâ€™s green now</p>",
        "id": 275386145,
        "sender_full_name": "Simon Sapin",
        "timestamp": 1647357087
    }
]