[
    {
        "content": "<p>In <a href=\"https://github.com/rust-lang/rust/pull/79057#issuecomment-727271631\">https://github.com/rust-lang/rust/pull/79057#issuecomment-727271631</a>, CI failed because the toolstate of the reference regressed, but it included no information whatsoever about <em>what</em> actually failed. Is there a way to see what's going on?</p>",
        "id": 216754230,
        "sender_full_name": "Jonas Schievink  [he/him]",
        "timestamp": 1605393679
    },
    {
        "content": "<div class=\"codehilite\"><pre><span></span><code>2020-11-14T21:47:49.4965348Z Testing rustbook src/doc/reference\n2020-11-14T21:48:07.8486089Z Error: One or more tests failed\n2020-11-14T21:48:07.8488268Z\n2020-11-14T21:48:07.8488599Z\n2020-11-14T21:48:07.8490324Z command did not execute successfully: &quot;/checkout/obj/build/x86_64-unknown-linux-gnu/stage0-tools-bin/rustbook&quot; &quot;test&quot; &quot;/checkout/src/doc/reference&quot;\n2020-11-14T21:48:07.8491207Z expected success, got: exit code: 101\n2020-11-14T21:48:07.8491493Z\n2020-11-14T21:48:07.8493920Z\n2020-11-14T21:48:07.8494626Z    finished in 18.352 seconds\n</code></pre></div>",
        "id": 216756238,
        "sender_full_name": "simulacrum",
        "timestamp": 1605396709
    },
    {
        "content": "<p>Seems odd</p>",
        "id": 216756239,
        "sender_full_name": "simulacrum",
        "timestamp": 1605396713
    },
    {
        "content": "<p>I'll post a PR to fix the lack of error messages.</p>",
        "id": 216760854,
        "sender_full_name": "Eric Huss",
        "timestamp": 1605402109
    },
    {
        "content": "<p>Tracked the problem to <a href=\"https://github.com/rust-lang/rust/issues/79003\">#79003</a>.</p>",
        "id": 216761823,
        "sender_full_name": "Eric Huss",
        "timestamp": 1605403925
    }
]